// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/jflex/oberon.flex


import exceptions.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class OberonScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\2\0\1\2"+
    "\2\0\1\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\0\1\13\11\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\0\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\2\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\33\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\33\1\47\1\33\1\50\1\0\1\51\3\0"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\2\33\1\34\1\35\1\36\1\37\1\40\1\33"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\33\1\47"+
    "\1\33\3\0\1\52\261\0\2\53\115\0\1\54\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\16\23\1\24\1\25\1\26\1\1"+
    "\2\2\1\27\1\30\1\31\1\32\1\33\5\23\1\34"+
    "\1\0\4\23\1\35\7\23\1\34\1\0\1\36\4\23"+
    "\2\37\1\23\1\0\1\23\1\40\6\23\1\0\1\23"+
    "\2\0\1\23\1\0\2\23\1\0\1\23\1\0\2\23"+
    "\1\41\1\23\1\0\1\23\2\0\3\23\2\41\1\0"+
    "\3\23\2\0\1\23\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\132\0\132\0\264\0\132"+
    "\0\132\0\132\0\132\0\132\0\132\0\341\0\u010e\0\u013b"+
    "\0\132\0\u0168\0\132\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\u040b\0\132\0\132\0\132\0\u0438\0\132\0\u0465"+
    "\0\132\0\u0492\0\132\0\132\0\132\0\u04bf\0\u04ec\0\u0519"+
    "\0\u0546\0\u0573\0\u02a3\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654"+
    "\0\u02a3\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f"+
    "\0\132\0\u07bc\0\132\0\u07e9\0\u0816\0\u0843\0\u0870\0\u02a3"+
    "\0\132\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951\0\u097e\0\u09ab"+
    "\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13"+
    "\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b"+
    "\0\u02a3\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89\0\u0db6"+
    "\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e"+
    "\0\u0f4b\0\u0f78\0\132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\3\32"+
    "\1\33\2\32\1\34\1\32\1\35\1\36\1\37\1\32"+
    "\1\40\1\32\1\41\1\42\1\32\1\43\1\44\1\45"+
    "\1\46\1\3\6\47\1\50\46\47\56\0\1\4\61\0"+
    "\1\51\61\0\2\16\5\0\26\52\20\0\2\17\5\0"+
    "\26\52\25\0\1\53\54\0\1\54\54\0\1\55\47\0"+
    "\2\32\5\0\17\32\1\56\6\32\20\0\2\32\5\0"+
    "\4\32\1\57\10\32\1\60\10\32\20\0\2\32\5\0"+
    "\15\32\1\61\10\32\20\0\2\32\5\0\10\32\1\62"+
    "\4\32\1\63\10\32\3\0\1\64\14\0\2\32\5\0"+
    "\12\32\1\65\1\32\1\66\11\32\20\0\2\32\5\0"+
    "\26\32\20\0\2\32\5\0\5\32\1\63\6\32\1\67"+
    "\11\32\20\0\2\32\5\0\15\32\1\70\10\32\20\0"+
    "\2\32\5\0\5\32\1\63\11\32\1\71\6\32\20\0"+
    "\2\32\5\0\17\32\1\72\6\32\20\0\2\32\5\0"+
    "\4\32\1\73\21\32\20\0\2\32\5\0\7\32\1\74"+
    "\15\32\1\75\20\0\2\32\5\0\1\76\25\32\20\0"+
    "\2\32\5\0\7\32\1\77\7\32\1\100\6\32\34\0"+
    "\1\101\6\0\1\102\23\0\1\103\62\0\2\52\5\0"+
    "\26\52\20\0\2\32\5\0\17\32\1\104\6\32\20\0"+
    "\2\32\5\0\6\32\1\105\17\32\20\0\2\32\5\0"+
    "\15\32\1\106\10\32\20\0\2\32\5\0\14\32\1\107"+
    "\11\32\20\0\2\32\5\0\23\32\1\110\2\32\52\0"+
    "\1\111\22\0\2\32\5\0\20\32\1\112\5\32\4\0"+
    "\1\113\13\0\2\32\5\0\3\32\1\63\22\32\20\0"+
    "\2\32\5\0\21\32\1\114\4\32\20\0\2\32\5\0"+
    "\3\32\1\115\22\32\20\0\2\32\5\0\15\32\1\116"+
    "\10\32\20\0\2\32\5\0\1\117\1\32\1\120\23\32"+
    "\20\0\2\32\5\0\4\32\1\121\21\32\20\0\2\32"+
    "\5\0\16\32\1\122\7\32\20\0\2\32\5\0\17\32"+
    "\1\63\6\32\20\0\2\32\5\0\10\32\1\123\15\32"+
    "\3\0\1\124\14\0\2\32\5\0\10\32\1\125\15\32"+
    "\3\0\1\126\44\0\1\127\24\0\2\32\5\0\1\130"+
    "\25\32\20\0\2\32\5\0\10\32\1\121\15\32\3\0"+
    "\1\131\14\0\2\32\5\0\12\32\1\132\13\32\20\0"+
    "\2\32\5\0\20\32\1\133\5\32\4\0\1\134\13\0"+
    "\2\32\5\0\4\32\1\63\3\32\1\135\15\32\3\0"+
    "\1\136\27\0\1\101\3\0\1\136\20\0\1\136\14\0"+
    "\2\32\5\0\4\32\1\137\21\32\20\0\2\32\5\0"+
    "\22\32\1\123\3\32\20\0\2\32\5\0\2\32\1\140"+
    "\23\32\20\0\2\32\5\0\3\32\1\141\22\32\20\0"+
    "\2\32\5\0\15\32\1\142\10\32\20\0\2\32\5\0"+
    "\14\32\1\63\11\32\20\0\2\32\5\0\4\32\1\63"+
    "\21\32\20\0\2\32\5\0\12\32\1\122\13\32\41\0"+
    "\1\143\33\0\2\32\5\0\21\32\1\144\4\32\50\0"+
    "\1\145\37\0\1\146\41\0\2\32\5\0\25\32\1\63"+
    "\43\0\1\101\31\0\2\32\5\0\4\32\1\147\21\32"+
    "\20\0\2\32\5\0\21\32\1\63\4\32\50\0\1\101"+
    "\24\0\2\32\5\0\5\32\1\63\20\32\34\0\1\101"+
    "\40\0\2\32\5\0\6\32\1\150\17\32\20\0\2\32"+
    "\5\0\4\32\1\151\21\32\20\0\2\32\5\0\17\32"+
    "\1\66\6\32\33\0\1\101\41\0\2\32\5\0\4\32"+
    "\1\152\21\32\33\0\1\153\56\0\1\154\37\0\2\32"+
    "\5\0\1\155\25\32\20\0\2\32\5\0\4\32\1\156"+
    "\21\32\20\0\2\32\5\0\3\32\1\157\22\32\20\0"+
    "\2\32\5\0\12\32\1\155\13\32\41\0\1\160\46\0"+
    "\1\161\41\0\2\32\5\0\14\32\1\141\11\32\20\0"+
    "\2\32\5\0\17\32\1\141\6\32\20\0\2\32\5\0"+
    "\22\32\1\162\3\32\43\0\1\163\57\0\1\163\26\0"+
    "\2\32\5\0\17\32\1\122\6\32\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4005];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\1\1\6\11\3\1\1\11"+
    "\1\1\1\11\17\1\3\11\1\1\1\11\1\1\1\11"+
    "\1\1\3\11\6\1\1\0\14\1\1\11\1\0\1\11"+
    "\5\1\1\11\1\1\1\0\10\1\1\0\1\1\2\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\4\1\1\0"+
    "\1\1\2\0\5\1\1\0\3\1\2\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private String debuginfo(String type) {
        return type + ": at line " + (yyline+1) + ", column " + (yycolumn+1) + ": " + yytext() + "\n";
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public String yylex() throws java.io.IOException, LexicalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case COMMENT: {
              throw new MismatchedCommentException("at line " + (yyline+1) + ", column " + (yycolumn+1));
            }  // fall though
            case 116: break;
            default:
              {
                return "EOF\n";
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalSymbolException("at line " + (yyline+1) + ", column " + (yycolumn+1));
            }
            // fall through
          case 34: break;
          case 2:
            { /* skip */
            }
            // fall through
          case 35: break;
          case 3:
            { return "#\n";
            }
            // fall through
          case 36: break;
          case 4:
            { return "&\n";
            }
            // fall through
          case 37: break;
          case 5:
            { return "LPAREN\n";
            }
            // fall through
          case 38: break;
          case 6:
            { return "RPAREN\n";
            }
            // fall through
          case 39: break;
          case 7:
            { return "*\n";
            }
            // fall through
          case 40: break;
          case 8:
            { return "+\n";
            }
            // fall through
          case 41: break;
          case 9:
            { return "COMMA\n";
            }
            // fall through
          case 42: break;
          case 10:
            { return "-\n";
            }
            // fall through
          case 43: break;
          case 11:
            { return "DOT\n";
            }
            // fall through
          case 44: break;
          case 12:
            { if(yylength() > 12) {
            throw new IllegalIntegerRangeException();
        }
        String octStr = yytext();
        for (char c : octStr.toCharArray()) {
            if (c < '0' || c > '7') {
                throw new IllegalOctalException();
            }
        }
        return debuginfo("Octal Integer" + Integer.parseInt(octStr, 8));
            }
            // fall through
          case 45: break;
          case 13:
            { if(yylength() > 12) {
            throw new IllegalIntegerRangeException();
        }
        return debuginfo("Decimal Integer" + Integer.parseInt(yytext()));
            }
            // fall through
          case 46: break;
          case 14:
            { return "COLON\n";
            }
            // fall through
          case 47: break;
          case 15:
            { return "SEMICOLON\n";
            }
            // fall through
          case 48: break;
          case 16:
            { return "<\n";
            }
            // fall through
          case 49: break;
          case 17:
            { return "=\n";
            }
            // fall through
          case 50: break;
          case 18:
            { return ">\n";
            }
            // fall through
          case 51: break;
          case 19:
            { if(yylength() > 24) {
            throw new IllegalIdentifierLengthException();
        }
        return debuginfo("Identifier");
            }
            // fall through
          case 52: break;
          case 20:
            { return "LBRACK\n";
            }
            // fall through
          case 53: break;
          case 21:
            { return "RBRACK\n";
            }
            // fall through
          case 54: break;
          case 22:
            { return "~\n";
            }
            // fall through
          case 55: break;
          case 23:
            { yybegin(COMMENT);
            }
            // fall through
          case 56: break;
          case 24:
            { throw new IllegalIntegerException();
            }
            // fall through
          case 57: break;
          case 25:
            { return ":=\n";
            }
            // fall through
          case 58: break;
          case 26:
            { return "<=\n";
            }
            // fall through
          case 59: break;
          case 27:
            { return ">=\n";
            }
            // fall through
          case 60: break;
          case 28:
            { return "RESERVED WORD\n";
            }
            // fall through
          case 61: break;
          case 29:
            { return "OR\n";
            }
            // fall through
          case 62: break;
          case 30:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 63: break;
          case 31:
            { return "DIV\n";
            }
            // fall through
          case 64: break;
          case 32:
            { return "MOD\n";
            }
            // fall through
          case 65: break;
          case 33:
            { return "KEYWORD\n";
            }
            // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
